### ISSUE TITLE
is the 2 gb supposed to be a bypass to aniviruses or

### ISSUE THREAD

**Issue by alternativebyte** [face-hh/wattesigma#2] opened 2024-09-23 19:10 UTC
is it just like that

**Comment by Badbird5907** [comment] 2024-09-24 00:37
yes'nt

**Comment by face-hh** [comment] 2024-09-24 15:06
No, it's the actual file size. I will try to decrease it in the next release.

**Comment by face-hh** [comment] 2024-09-24 15:06
Duplicate of #1

**Closed** 2024-09-24 15:06 UTC

**Comment by Unknown303YT** [comment] 2024-09-25 07:42
why open and close, @face-hh

**Comment by face-hh** [comment] 2024-09-25 07:55
> why open and close, @face-hh 

I closed it as "not planned" by mistake, which was not accurate. I closed it again as "completed", because it's a duplicate and will be fixed in the next release
